## Import needed libraries

In [1]:
import pandas as pd
import numpy as np
import requests

### Load table into database

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]

In [3]:
for col in df.columns: 
    print(col) 

0
1
2
3
4
5
6
7
8


In [4]:
df.columns = ['Row_1', 'Row_2', 'Row_3', 'Row_4','Row_5', 'Row_6', 'Row_7', 'Row_8','Row_9']

In [5]:
x = df['Row_1'].unique().tolist()
x1 = df['Row_2'].unique().tolist()
x2 = df['Row_3'].unique().tolist()
x3 = df['Row_4'].unique().tolist()
x4 = df['Row_5'].unique().tolist()
x5 = df['Row_6'].unique().tolist()
x6 = df['Row_7'].unique().tolist()
x7 = df['Row_8'].unique().tolist()
x8 = df['Row_9'].unique().tolist()

Creating a new list of values to make a new Data frame to work with

In [6]:
z = x + x1 +x2 +x3 +x4 +x5 +x6 +x7 +x8
new_df = pd.DataFrame(z)

for col in new_df.columns: 
    print(col) 
    
new_df.columns = ['Locate']

0


Modifying string data to extract needed column values

In [7]:
new_df['Locate'] = new_df[~new_df.Locate.str.contains("Not assigned", na=False)]
new_df = new_df.dropna()

new_df['Postal_Code'] = new_df['Locate'].str[:3]

new_df['Borough'] = new_df['Locate'].str[3:]

new_df['Borough']= new_df['Borough'].str.split("(", n = 1, expand = True)

new_df['Neighborhood'] = new_df['Locate'].str[3:]

In [8]:
new = new_df['Neighborhood'].str.split("(", n = 1, expand = True) 

new_df['Borough']= new[0] 

new_df['Neighborhood']= new[1] 

Clean up

In [9]:
new_df.drop(columns =["Locate"], inplace = True) 
new_df['Neighborhood'] = new_df['Neighborhood'].str.replace(')',' ')
new_df['Neighborhood'] = new_df['Neighborhood'].str.replace('/',', ')
new_df.reset_index()

index Postal_Code             Borough  \
0        1         M1B         Scarborough   
1        2         M1C         Scarborough   
2        3         M1E         Scarborough   
3        4         M1G         Scarborough   
4        5         M1H         Scarborough   
..     ...         ...                 ...   
98     170         M9N                York   
99     171         M9P           Etobicoke   
100    172         M9R           Etobicoke   
101    175         M9V           Etobicoke   
102    176         M9W  EtobicokeNorthwest   

                                          Neighborhood  
0                                    Malvern ,  Rouge   
1          Rouge Hill ,  Port Union ,  Highland Creek   
2               Guildwood ,  Morningside ,  West Hill   
3                                              Woburn   
4                                           Cedarbrae   
..                                                 ...  
98                                             Weston   
99                                          Westmount   
100  Kingsview Village ,  St. Phillips ,  Martin Gr...  
101  South Steeles ,  Silverstone ,  Humbergate ,  ...  
102  Clairville ,  Humberwood ,  Woodbine Downs ,  ...  

[103 rows x 4 columns]

In [10]:
new_df.shape

(103, 3)

In [11]:
new_df.head(20)

Postal_Code      Borough                                       Neighborhood
1          M1B  Scarborough                                  Malvern ,  Rouge 
2          M1C  Scarborough        Rouge Hill ,  Port Union ,  Highland Creek 
3          M1E  Scarborough             Guildwood ,  Morningside ,  West Hill 
4          M1G  Scarborough                                            Woburn 
5          M1H  Scarborough                                         Cedarbrae 
6          M1J  Scarborough                               Scarborough Village 
7          M1K  Scarborough   Kennedy Park ,  Ionview ,  East Birchmount Park 
8          M1L  Scarborough               Golden Mile ,  Clairlea ,  Oakridge 
9          M1M  Scarborough  Cliffside ,  Cliffcrest ,  Scarborough Village...
10         M1N  Scarborough                     Birch Cliff ,  Cliffside West 
11         M1P  Scarborough  Dorset Park ,  Wexford Heights ,  Scarborough ...
12         M1R  Scarborough                               Wexford ,  Maryvale 
13         M1S  Scarborough                                         Agincourt 
14         M1T  Scarborough       Clarks Corners ,  Tam O'Shanter ,  Sullivan 
15         M1V  Scarborough  Milliken ,  Agincourt North ,  Steeles East , ...
16         M1W  Scarborough                   Steeles West ,  L'Amoreaux West 
17         M1X  Scarborough                                       Upper Rouge 
25         M2H   North York                                 Hillcrest Village 
26         M2J   North York                  Fairview ,  Henry Farm ,  Oriole 
27         M2K   North York                                   Bayview Village

## Finding the coordinates to go with postal codes

In [12]:
df1 = pd.read_csv('https://cocl.us/Geospatial_data')

In [13]:
df1.columns = ['Postal_Code','Latitude','Longitude']

In [14]:
New_df = pd.merge(new_df,
                 df1[['Postal_Code','Latitude','Longitude']],
                 on='Postal_Code')

Table Now with GPS Cooordinates

In [15]:
New_df

Postal_Code             Borough  \
0           M1B         Scarborough   
1           M1C         Scarborough   
2           M1E         Scarborough   
3           M1G         Scarborough   
4           M1H         Scarborough   
..          ...                 ...   
98          M9N                York   
99          M9P           Etobicoke   
100         M9R           Etobicoke   
101         M9V           Etobicoke   
102         M9W  EtobicokeNorthwest   

                                          Neighborhood   Latitude  Longitude  
0                                    Malvern ,  Rouge   43.806686 -79.194353  
1          Rouge Hill ,  Port Union ,  Highland Creek   43.784535 -79.160497  
2               Guildwood ,  Morningside ,  West Hill   43.763573 -79.188711  
3                                              Woburn   43.770992 -79.216917  
4                                           Cedarbrae   43.773136 -79.239476  
..                                                 ...        ...        ...  
98                                             Weston   43.706876 -79.518188  
99                                          Westmount   43.696319 -79.532242  
100  Kingsview Village ,  St. Phillips ,  Martin Gr...  43.688905 -79.554724  
101  South Steeles ,  Silverstone ,  Humbergate ,  ...  43.739416 -79.588437  
102  Clairville ,  Humberwood ,  Woodbine Downs ,  ...  43.706748 -79.594054  

[103 rows x 5 columns]

# Make Clusters of different nighborhoods in Toronto

In [16]:
import random 
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn.cluster import KMeans 
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import StandardScaler
import folium
print('Libraries imported.')

Libraries imported.


In [17]:
dfk = New_df.drop(['Postal_Code','Borough','Neighborhood'], axis = 1)
dfk.head()

Latitude  Longitude
0  43.806686 -79.194353
1  43.784535 -79.160497
2  43.763573 -79.188711
3  43.770992 -79.216917
4  43.773136 -79.239476

In [18]:
X = dfk.values[:,1:]
X = np.nan_to_num(X)
cluster_dataset = StandardScaler().fit_transform(X)
cluster_dataset

array([[ 2.09777597],
       [ 2.44798852],
       [ 2.15613628],
       [ 1.86437197],
       [ 1.6310228 ],
       [ 1.6310228 ],
       [ 1.39772948],
       [ 1.16449306],
       [ 1.6310228 ],
       [ 1.3685726 ],
       [ 1.28110403],
       [ 1.04789553],
       [ 1.39772948],
       [ 0.96045696],
       [ 1.16449306],
       [ 0.81474393],
       [ 1.98106673],
       [ 0.3486083 ],
       [ 0.523382  ],
       [ 0.1156253 ],
       [ 0.23210904],
       [-0.1173008 ],
       [-0.1173008 ],
       [-0.0299605 ],
       [-0.46658445],
       [ 0.69818881],
       [ 0.465121  ],
       [ 0.58164715],
       [-0.46658445],
       [-0.9320953 ],
       [-0.6993678 ],
       [-1.13568453],
       [-1.01935285],
       [-1.28107896],
       [ 0.84388426],
       [ 0.90216906],
       [ 0.81474393],
       [ 1.07704414],
       [ 0.3486083 ],
       [ 0.49425098],
       [ 0.61078127],
       [ 0.465121  ],
       [ 0.84388426],
       [ 0.58164715],
       [ 0.08650566],
       [ 0

In [19]:
num_clusters = 3

k_means = KMeans(init="k-means++", n_clusters=num_clusters, n_init=12)
k_means.fit(cluster_dataset)
labels = k_means.labels_

print(labels)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2
 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 0 1 1 1 1 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [20]:
New_df["Labels"] = labels
New_df.head(20)

Postal_Code      Borough  \
0          M1B  Scarborough   
1          M1C  Scarborough   
2          M1E  Scarborough   
3          M1G  Scarborough   
4          M1H  Scarborough   
5          M1J  Scarborough   
6          M1K  Scarborough   
7          M1L  Scarborough   
8          M1M  Scarborough   
9          M1N  Scarborough   
10         M1P  Scarborough   
11         M1R  Scarborough   
12         M1S  Scarborough   
13         M1T  Scarborough   
14         M1V  Scarborough   
15         M1W  Scarborough   
16         M1X  Scarborough   
17         M2H   North York   
18         M2J   North York   
19         M2K   North York   

                                         Neighborhood   Latitude  Longitude  \
0                                   Malvern ,  Rouge   43.806686 -79.194353   
1         Rouge Hill ,  Port Union ,  Highland Creek   43.784535 -79.160497   
2              Guildwood ,  Morningside ,  West Hill   43.763573 -79.188711   
3                                             Woburn   43.770992 -79.216917   
4                                          Cedarbrae   43.773136 -79.239476   
5                                Scarborough Village   43.744734 -79.239476   
6    Kennedy Park ,  Ionview ,  East Birchmount Park   43.727929 -79.262029   
7                Golden Mile ,  Clairlea ,  Oakridge   43.711112 -79.284577   
8   Cliffside ,  Cliffcrest ,  Scarborough Village...  43.716316 -79.239476   
9                      Birch Cliff ,  Cliffside West   43.692657 -79.264848   
10  Dorset Park ,  Wexford Heights ,  Scarborough ...  43.757410 -79.273304   
11                               Wexford ,  Maryvale   43.750072 -79.295849   
12                                         Agincourt   43.794200 -79.262029   
13       Clarks Corners ,  Tam O'Shanter ,  Sullivan   43.781638 -79.304302   
14  Milliken ,  Agincourt North ,  Steeles East , ...  43.815252 -79.284577   
15                   Steeles West ,  L'Amoreaux West   43.799525 -79.318389   
16                                       Upper Rouge   43.836125 -79.205636   
17                                 Hillcrest Village   43.803762 -79.363452   
18                  Fairview ,  Henry Farm ,  Oriole   43.778517 -79.346556   
19                                   Bayview Village   43.786947 -79.385975   

    Labels  
0        2  
1        2  
2        2  
3        2  
4        2  
5        2  
6        2  
7        2  
8        2  
9        2  
10       2  
11       2  
12       2  
13       2  
14       2  
15       2  
16       2  
17       1  
18       1  
19       1

## Will create points to show centre of clusters

In [21]:
 New_df1 = New_df.groupby('Labels').mean()

In [22]:
New_df1['Label'] = {'East', 'Center', 'West'}

In [23]:
k_means_labels = k_means.labels_
k_means_labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
k_means_cluster_centers = k_means.cluster_centers_
k_means_cluster_centers

array([[-1.23861156],
       [ 0.09055732],
       [ 1.36092661]])

### Plotting the map

In [25]:

map_toronto = folium.Map(location=[43.746157, -79.265587], zoom_start=10)


for lat, lng, borough, neighborhood, borough1  in zip(New_df['Latitude'], New_df['Longitude'], New_df['Labels'], New_df['Neighborhood'], New_df['Borough']):
    label = '{}, {}'.format(neighborhood, borough1)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=10,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity= (0.1 + borough/2),
        parse_html=False).add_to(map_toronto)  

## Three markers to identify three groups zones    

for lat, lng, labe in zip(New_df1['Latitude'], New_df1['Longitude'], New_df1['Label']):
    label = '{}'.format( labe)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=60,
        popup=label,
        color=None,
        fill=True,
        fill_color='red',
        fill_opacity= 0.2,
        parse_html=False).add_to(map_toronto)      
    
map_toronto

The map display each neighborhood, with color shades to indicate those belonging to similar groupings. 
The red circles indicate the centre of each group.